name: generate-snake
on:
  schedule: [{cron: "0 */24 * * *"}]  # runs once per day
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Priya2149   # <-- replace with your GitHub username
          outputs: |
            dist/snake.svg
      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
